#!/usr/bin/env bash
#
# Este script se preparo para ser usado con el comando Cron.
# La variable 'CURRENT_DIR' se debe instanciar al directorio donde esta 
# desplegada esta herramienta.
#
# Author: John Sanabria
# Date: 2019-09-09
#
CURRENT_DIR="/cluster/condor/vagrant/_extract"
CURRENT_DATE=$( date +'%s' )
cd ${CURRENT_DIR}
LOGFILE="${CURRENT_DIR}/logfile.log"
echo "[${CURRENT_DATE}] $(pwd)" >> ${LOGFILE}
echo "[${CURRENT_DATE}] A punto de ejecutar '${CURRENT_DIR}/prepararEntornoExe'" >> ${LOGFILE}
SALIDA=$( ${CURRENT_DIR}/prepararEntornoExe )
DIR=$(echo ${SALIDA} | cut -d '[' -f 2 | cut -d ']' -f 1)
echo "[${CURRENT_DATE}] Yendo a directorio ${CURRENT_DIR}/${DIR}" >> ${LOGFILE}
cd ${CURRENT_DIR}/${DIR}
echo "[${CURRENT_DATE}] Ejecutando condor_submit_dag" >> ${LOGFILE} 
condor_submit_dag historyXML2CSV.dag
if [ ! $? -eq 0 ]; then
	echo "[${CURRENT_DATE}] Error al someter tarea" >> ${LOGFILE} 
	exit -1
fi

